[server]
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 200
enableWebsocketCompression = false
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
base = "light"
primaryColor = "#2563eb"
backgroundColor = "#f1f5f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"
